```{r}
library(tidyverse)
library(dplyr)


answers <- read_csv('answers.csv')
question_tags <- read_csv('question_tags.csv')
questions <- read_csv('questions.csv')
tags <- read_csv('tags.csv')



```



1.1, 
```{r}
data_join <- left_join(questions, question_tags, by = c("id" = "question_id"))

#1.3

tag_fin <- left_join(answers, tags, by = c("question_id" = "id"))

#1.3 y 1.4

questions_with_tags <- tag_fin%>%
  mutate(tag_name = replace_na(tag_name, "only-r"))

```
2
```{r}
#2.1

info_2_1 <- questions_with_tags%>%
  group_by(tag_name)

#2.2
info_2_2 <- questions_with_tags%>%
  summarize(mean_score = mean(score))

#2.3

info_2_3 <- info_2_2%>%
  arrange(desc(mean_score))

```
3
```{r}
#3.1
info_3 <- questions
data_3 <- answers

info_3_1 <-  info_3 %>%
  inner_join(data_3, by = c("id" = "question_id"), suffix = c("_question", "_answer"))

#3.2

info_3_2 <- info_3_1%>%
  mutate(gap = creation_date_answer - creation_date_question)

```
4

```{r}

#4.1

answer_counts <- answers %>%
  count(question_id, sort = TRUE)

#4.2

data_4_2 <- left_join(questions, answer_counts, by = c("id" = "question_id"))

#4.3 y 4.4

questions_answer_counts <- data_4_2%>%
  mutate(n = replace_na(n, 0))

```
5
```{r}

#5.1 y 5.2

info_5_1 <- question_tags %>%
  inner_join(questions_answer_counts, by = c("question_id" = "id"))%>%
  inner_join(tags, by = c("tag_id" = "id"))




```

